last isa

diff --git a/.github/workflows/ssh.yml b/.github/workflows/ssh.yml
--- a/.github/workflows/ssh.yml
+++ b/.github/workflows/ssh.yml
@@ -1,4 +1,4 @@
-name: Deploy TapgoUI-Kiosk via SSHs
+name: Deploy TapgoUI-Kiosk via SSH abdo
 
 on:
   push:
@@ -22,7 +22,7 @@ jobs:
               echo "========== Deployment Started: \$(date) =========="
               echo "Processing TapgoUI-Kiosk..."
 
-              cd /home/ubuntu/TapgoUI-Kiosk || { echo "[ERROR] Directory TapgoUI-Kiosk not found"; exit 1; }
+              cd ~/TapgoUI-Kiosk || { echo "[ERROR] Directory TapgoUI-Kiosk not found"; exit 1; }
 
               echo "[INFO] Pulling latest changes from dev branch..."
               git pull origin dev || { echo "[ERROR] Git pull failed"; exit 1; }
